package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.triggers.schedule
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'v2_BT_branch1_Composite'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("v2_BT_branch1_Composite")) {
    check(type == BuildTypeSettings.Type.COMPOSITE) {
        "Unexpected option value: type = $type"
    }
    type = BuildTypeSettings.Type.REGULAR

    vcs {
        remove(DslContext.settingsRoot.id!!)
        add(RelativeId("HttpsGithubComKevinZhangEATeamcityTestRefsHeadsMain_2"))
    }

    triggers {
        remove {
            schedule {
                schedulingPolicy = daily {
                    hour = 3
                    minute = 0
                }
                branchFilter = "+:refs/heads/branch1"
                triggerBuild = always()
                withPendingChangesOnly = false

                enforceCleanCheckout = true
                buildParams {
                    param("CLEAN_BUILD", "true")
                    param("RUN_MODE", "nightly")
                }
            }
        }
    }
}
