package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.triggers.VcsTrigger
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'v2_BT_branch1_Composite'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("v2_BT_branch1_Composite")) {
    vcs {

        check(branchFilter == "+:refs/heads/branch1") {
            "Unexpected option value: branchFilter = $branchFilter"
        }
        branchFilter = "+:*"
    }

    triggers {
        val trigger1 = find<VcsTrigger> {
            vcs {
                branchFilter = "+:refs/heads/branch1"
                watchChangesInDependencies = true
            }
        }
        trigger1.apply {
            branchFilter = "+:branch1"

        }
    }
}
