package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'v2_BT_branch1_Composite'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("v2_BT_branch1_Composite")) {
    vcs {

        check(branchFilter == "+:refs/heads/branch1") {
            "Unexpected option value: branchFilter = $branchFilter"
        }
        branchFilter = "+:*"
    }
}
