package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'v2_BT_Agent_Init_Linux'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("v2_BT_Agent_Init_Linux")) {
    params {
        expect {
            select("agent", "", display = ParameterDisplay.PROMPT,
                    options = listOf("%teamcity.agents.available%"))
        }
        update {
            select("agent", "", display = ParameterDisplay.PROMPT,
                    options = listOf("agents"))
        }
    }
}
