package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'v2_BT_branch1_client_android_debug'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("v2_BT_branch1_client_android_debug")) {
    vcs {
        add(DslContext.settingsRoot.id!!)
    }
}
