package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComKevinZhangEATeamcityTestRefsHeadsMain_2'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComKevinZhangEATeamcityTestRefsHeadsMain_2")
    name = "https://github.com/KevinZhangEA/teamcityTest#refs/heads/main"
    url = "https://github.com/KevinZhangEA/teamcityTest"
    branch = "refs/heads/main"
    authMethod = password {
        userName = "KevinZhangEA"
        password = "credentialsJSON:5ea621b2-739f-42d4-a0cb-fa3b376a184a"
    }
}))

